# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nemotron-super-models
spec:
  storageClassName: ""
  capacity:
    storage: 200Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - region ${AWS_REGION}
  csi:
    driver: s3.csi.aws.com
    volumeHandle: nemotron-super-models
    volumeAttributes:
      bucketName: ${S3_BUCKET}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nemotron-super-models
spec:
  storageClassName: ""
  volumeName: nemotron-super-models
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 200Gi
