# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_REGION}
  version: "1.31"

iam:
  withOIDC: true

managedNodeGroups:
  - name: gpu-g5-12xl
    instanceType: g5.12xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 500
    volumeType: gp3
    labels:
      role: gpu-worker
    tags:
      nodegroup-purpose: vllm-inference

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: eks-pod-identity-agent
  - name: aws-mountpoint-s3-csi-driver
    attachPolicyARNs:
      - "arn:aws:iam::${AWS_ACCOUNT_ID}:policy/MountpointS3-${CLUSTER_NAME}"
